// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#ifndef _CNC_HMI_UI_H
#define _CNC_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_main.h"
#include "screens/ui_seleccionarTarea.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_plus_png);    // assets/plus.png
LV_IMG_DECLARE(ui_img_hibernacion_png);    // assets/hibernacion.png
LV_IMG_DECLARE(ui_img_680980976);    // assets/boton-de-pausa (1).png
LV_IMG_DECLARE(ui_img_324518500);    // assets/punta-de-flecha-del-boton-de-reproduccion.png
LV_IMG_DECLARE(ui_img_home_24_png);    // assets/home 24.png
LV_IMG_DECLARE(ui_img_745144479);    // assets/flecha-izquierda.png

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
