// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#include "ui.h"

void parado_total(lv_event_t * e)
{
	// Your code here
}

void listar_maquinas(lv_event_t * e)
{
	// Your code here
}

void agregar_tarea(lv_event_t * e)
{
	// Your code here
}

void pauseMachine(lv_event_t * e)
{
	// Your code here
}

void iniciarCorte(lv_event_t * e)
{
	// Your code here
}

void mover_x_pos(lv_event_t * e)
{
	// Your code here
}

void mover_x_neg(lv_event_t * e)
{
	// Your code here
}

void mover_y_pos(lv_event_t * e)
{
	// Your code here
}

void mover_y_neg(lv_event_t * e)
{
	// Your code here
}

void mover_z_pos(lv_event_t * e)
{
	// Your code here
}

void mover_z_neg(lv_event_t * e)
{
	// Your code here
}

void parado_de_emergencia(lv_event_t * e)
{
	// Your code here
}

void home_positions(lv_event_t * e)
{
	// Your code here
}

void asignar_tarea(lv_event_t * e)
{
	// Your code here
}

void retrocederMain(lv_event_t * e)
{
	// Your code here
}
