// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_main_screen_relocalize(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_topBar;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_allStop;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_machines;
extern lv_obj_t * ui_listMaquinas;
extern lv_obj_t * ui_visualize;
extern lv_obj_t * ui_lblposx;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_lblposy;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_lblposz;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_stopMachine;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_btnHome;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

