// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#include "../ui.h"

lv_obj_t * ui_main = NULL;
lv_obj_t * ui_topBar = NULL;
lv_obj_t * ui_title = NULL;
lv_obj_t * ui_allStop = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_machines = NULL;
lv_obj_t * ui_listMaquinas = NULL;
lv_obj_t * ui_visualize = NULL;
lv_obj_t * ui_lblposx = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_lblposy = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_lblposz = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_home = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_stopMachine = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_btnHome = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar = lv_obj_create(ui_main);
    lv_obj_set_width(ui_topBar, 780);
    lv_obj_set_height(ui_topBar, 50);
    lv_obj_set_x(ui_topBar, 0);
    lv_obj_set_y(ui_topBar, 10);
    lv_obj_set_align(ui_topBar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_topBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_radius(ui_topBar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "CENTRAL CONTROL");

    ui_allStop = lv_btn_create(ui_topBar);
    lv_obj_set_width(ui_allStop, 100);
    lv_obj_set_height(ui_allStop, 40);
    lv_obj_set_align(ui_allStop, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_allStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_allStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_allStop, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_allStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_allStop);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "STOP ALL");

    ui_machines = lv_obj_create(ui_main);
    lv_obj_set_width(ui_machines, 200);
    lv_obj_set_height(ui_machines, 400);
    lv_obj_set_x(ui_machines, 10);
    lv_obj_set_y(ui_machines, -10);
    lv_obj_set_align(ui_machines, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_machines, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_listMaquinas = lv_roller_create(ui_machines);
    lv_roller_set_options(ui_listMaquinas, "Machine 1\nMacine 2", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_listMaquinas, lv_pct(100));
    lv_obj_set_height(ui_listMaquinas, lv_pct(100));
    lv_obj_set_align(ui_listMaquinas, LV_ALIGN_CENTER);

    ui_visualize = lv_obj_create(ui_main);
    lv_obj_set_width(ui_visualize, 300);
    lv_obj_set_height(ui_visualize, 400);
    lv_obj_set_x(ui_visualize, -25);
    lv_obj_set_y(ui_visualize, -10);
    lv_obj_set_align(ui_visualize, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_visualize, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblposx = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_lblposx, 100);
    lv_obj_set_height(ui_lblposx, 70);
    lv_obj_set_x(ui_lblposx, 80);
    lv_obj_set_y(ui_lblposx, -101);
    lv_obj_set_align(ui_lblposx, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lblposx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lblposx, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblposx, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lblposx, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lblposx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_lblposx, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_lblposx, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_lblposx);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "X: 0");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label7, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblposy = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_lblposy, 100);
    lv_obj_set_height(ui_lblposy, 70);
    lv_obj_set_x(ui_lblposy, -80);
    lv_obj_set_y(ui_lblposy, -44);
    lv_obj_set_align(ui_lblposy, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lblposy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lblposy, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblposy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lblposy, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lblposy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_lblposy, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_lblposy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_lblposy);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Y: 0");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label1, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblposz = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_lblposz, 100);
    lv_obj_set_height(ui_lblposz, 70);
    lv_obj_set_x(ui_lblposz, -80);
    lv_obj_set_y(ui_lblposz, -145);
    lv_obj_set_align(ui_lblposz, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lblposz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lblposz, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblposz, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lblposz, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lblposz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_lblposz, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_lblposz, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_lblposz);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Z: 0");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label2, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_visualize);
    lv_obj_set_width(ui_TextArea1, 250);
    lv_obj_set_height(ui_TextArea1, 150);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_TextArea1, "comands...");

    ui_home = lv_obj_create(ui_main);
    lv_obj_set_width(ui_home, 250);
    lv_obj_set_height(ui_home, 400);
    lv_obj_set_x(ui_home, -10);
    lv_obj_set_y(ui_home, -10);
    lv_obj_set_align(ui_home, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel10, 70);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_x(ui_Panel10, 70);
    lv_obj_set_y(ui_Panel10, -96);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel10, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "+X");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel1, 70);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -70);
    lv_obj_set_y(ui_Panel1, -93);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "-X");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel2, 70);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -160);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+Y");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel3, 70);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -30);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "-Y");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel4, 70);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, -70);
    lv_obj_set_y(ui_Panel4, 20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "+Z");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_home);
    lv_obj_set_width(ui_Panel5, 70);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_x(ui_Panel5, 78);
    lv_obj_set_y(ui_Panel5, 20);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "-Z");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_home);
    lv_dropdown_set_options(ui_Dropdown1, "predetermined\n0.1mm\n1.0mm\n10mm");
    lv_obj_set_width(ui_Dropdown1, 200);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, 90);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_stopMachine = lv_btn_create(ui_home);
    lv_obj_set_width(ui_stopMachine, 230);
    lv_obj_set_height(ui_stopMachine, 50);
    lv_obj_set_align(ui_stopMachine, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_stopMachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stopMachine, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopMachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_stopMachine);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "STOP MACHINE");

    ui_btnHome = lv_obj_create(ui_home);
    lv_obj_set_width(ui_btnHome, 40);
    lv_obj_set_height(ui_btnHome, 40);
    lv_obj_set_x(ui_btnHome, 0);
    lv_obj_set_y(ui_btnHome, -96);
    lv_obj_set_align(ui_btnHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnHome, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_btnHome);
    lv_img_set_src(ui_Image4, &ui_img_home_24_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 230);

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_topBar = NULL;
    ui_title = NULL;
    ui_allStop = NULL;
    ui_Label5 = NULL;
    ui_machines = NULL;
    ui_listMaquinas = NULL;
    ui_visualize = NULL;
    ui_lblposx = NULL;
    ui_Label7 = NULL;
    ui_lblposy = NULL;
    ui_Label1 = NULL;
    ui_lblposz = NULL;
    ui_Label2 = NULL;
    ui_TextArea1 = NULL;
    ui_home = NULL;
    ui_Panel10 = NULL;
    ui_Label8 = NULL;
    ui_Panel1 = NULL;
    ui_Label4 = NULL;
    ui_Panel2 = NULL;
    ui_Label6 = NULL;
    ui_Panel3 = NULL;
    ui_Label9 = NULL;
    ui_Panel4 = NULL;
    ui_Label10 = NULL;
    ui_Panel5 = NULL;
    ui_Label11 = NULL;
    ui_Dropdown1 = NULL;
    ui_stopMachine = NULL;
    ui_Label12 = NULL;
    ui_btnHome = NULL;
    ui_Image4 = NULL;

}

void ui_main_screen_relocalize(void)
{
    // label widgets on screen

}
