// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#include "../ui.h"

lv_obj_t * ui_main = NULL;
lv_obj_t * ui_topBar = NULL;
lv_obj_t * ui_title = NULL;
lv_obj_t * ui_allStop = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_uiLabelStatusConn = NULL;
lv_obj_t * ui_machines = NULL;
lv_obj_t * ui_listMaquinas = NULL;
lv_obj_t * ui_agregarTareas = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_visualize = NULL;
lv_obj_t * ui_posx = NULL;
lv_obj_t * ui_lblposx = NULL;
lv_obj_t * ui_posy = NULL;
lv_obj_t * ui_lblposy = NULL;
lv_obj_t * ui_posz = NULL;
lv_obj_t * ui_lblposz = NULL;
lv_obj_t * ui_state = NULL;
lv_obj_t * ui_isWork = NULL;
lv_obj_t * ui_lblState = NULL;
lv_obj_t * ui_imgState = NULL;
lv_obj_t * ui_areaComands = NULL;
lv_obj_t * ui_btnStop = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_btnPlay = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_controller = NULL;
lv_obj_t * ui_btnXpos = NULL;
lv_obj_t * ui_lblXpos = NULL;
lv_obj_t * ui_btnXneg = NULL;
lv_obj_t * ui_lblXneg = NULL;
lv_obj_t * ui_btnYpos = NULL;
lv_obj_t * ui_lblYpos = NULL;
lv_obj_t * ui_btnYneg = NULL;
lv_obj_t * ui_lblYneg = NULL;
lv_obj_t * ui_btnZpos = NULL;
lv_obj_t * ui_lblZpos = NULL;
lv_obj_t * ui_btnZneg = NULL;
lv_obj_t * ui_lblZneg = NULL;
lv_obj_t * ui_pasos = NULL;
lv_obj_t * ui_stopMachine = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_btnHome = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions
void ui_event_allStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        parado_total(e);
    }
}

void ui_event_listMaquinas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        listar_maquinas(e);
    }
}

void ui_event_agregarTareas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        agregar_tarea(e);
    }
}

void ui_event_btnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pauseMachine(e);
    }
}

void ui_event_btnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        iniciarCorte(e);
    }
}

void ui_event_btnXpos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_x_pos(e);
    }
}

void ui_event_btnXneg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_x_neg(e);
    }
}

void ui_event_btnYpos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_y_pos(e);
    }
}

void ui_event_btnYneg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_y_neg(e);
    }
}

void ui_event_btnZpos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_z_pos(e);
    }
}

void ui_event_btnZneg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mover_z_neg(e);
    }
}

void ui_event_stopMachine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        parado_de_emergencia(e);
    }
}

void ui_event_btnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_positions(e);
    }
}

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar = lv_obj_create(ui_main);
    lv_obj_set_width(ui_topBar, 780);
    lv_obj_set_height(ui_topBar, 50);
    lv_obj_set_x(ui_topBar, 0);
    lv_obj_set_y(ui_topBar, 10);
    lv_obj_set_align(ui_topBar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_topBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_radius(ui_topBar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "CENTRAL CONTROL");

    ui_allStop = lv_btn_create(ui_topBar);
    lv_obj_set_width(ui_allStop, 100);
    lv_obj_set_height(ui_allStop, 40);
    lv_obj_set_align(ui_allStop, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_allStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_allStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_allStop, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_allStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_allStop);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "STOP ALL");

    ui_uiLabelStatusConn = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_uiLabelStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelStatusConn, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_uiLabelStatusConn, "--");
    lv_obj_set_style_text_color(ui_uiLabelStatusConn, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelStatusConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelStatusConn, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_machines = lv_obj_create(ui_main);
    lv_obj_set_width(ui_machines, 200);
    lv_obj_set_height(ui_machines, 400);
    lv_obj_set_x(ui_machines, 10);
    lv_obj_set_y(ui_machines, -10);
    lv_obj_set_align(ui_machines, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_machines, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_listMaquinas = lv_roller_create(ui_machines);
    lv_roller_set_options(ui_listMaquinas, "Machine 1\nMachine 2\nMachine 3\nMachine 4", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_listMaquinas, lv_pct(100));
    lv_obj_set_height(ui_listMaquinas, lv_pct(70));
    lv_obj_set_align(ui_listMaquinas, LV_ALIGN_TOP_MID);

    ui_agregarTareas = lv_btn_create(ui_machines);
    lv_obj_set_width(ui_agregarTareas, lv_pct(100));
    lv_obj_set_height(ui_agregarTareas, lv_pct(10));
    lv_obj_set_align(ui_agregarTareas, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_agregarTareas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_agregarTareas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_agregarTareas);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_x(ui_Label8, lv_pct(7));
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "Agregar Tarea");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_agregarTareas);
    lv_img_set_src(ui_Image1, &ui_img_plus_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_x(ui_Image1, lv_pct(-9));
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_visualize = lv_obj_create(ui_main);
    lv_obj_set_width(ui_visualize, 300);
    lv_obj_set_height(ui_visualize, 400);
    lv_obj_set_x(ui_visualize, -25);
    lv_obj_set_y(ui_visualize, -10);
    lv_obj_set_align(ui_visualize, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_visualize, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_posx = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_posx, 90);
    lv_obj_set_height(ui_posx, 60);
    lv_obj_set_x(ui_posx, 60);
    lv_obj_set_y(ui_posx, -100);
    lv_obj_set_align(ui_posx, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_posx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_posx, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_posx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_posx, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_posx, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_posx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_posx, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_posx, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblposx = lv_label_create(ui_posx);
    lv_obj_set_width(ui_lblposx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblposx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblposx, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblposx, "X: 0");
    lv_obj_set_style_text_font(ui_lblposx, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblposx, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_posy = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_posy, 90);
    lv_obj_set_height(ui_posy, 60);
    lv_obj_set_x(ui_posy, -60);
    lv_obj_set_y(ui_posy, -60);
    lv_obj_set_align(ui_posy, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_posy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_posy, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_posy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_posy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_posy, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_posy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_posy, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_posy, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblposy = lv_label_create(ui_posy);
    lv_obj_set_width(ui_lblposy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblposy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblposy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblposy, "Y: 0");
    lv_obj_set_style_text_font(ui_lblposy, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblposy, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_posz = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_posz, 90);
    lv_obj_set_height(ui_posz, 60);
    lv_obj_set_x(ui_posz, -60);
    lv_obj_set_y(ui_posz, -145);
    lv_obj_set_align(ui_posz, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_posz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_posz, lv_color_hex(0xE3DDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_posz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_posz, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_posz, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_posz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_posz, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_posz, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblposz = lv_label_create(ui_posz);
    lv_obj_set_width(ui_lblposz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblposz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblposz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblposz, "Z: 0");
    lv_obj_set_style_text_font(ui_lblposz, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblposz, lv_color_hex(0xD4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblposz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_state = lv_obj_create(ui_visualize);
    lv_obj_set_height(ui_state, 170);
    lv_obj_set_width(ui_state, lv_pct(100));
    lv_obj_set_align(ui_state, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_state, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_isWork = lv_obj_create(ui_state);
    lv_obj_set_width(ui_isWork, lv_pct(100));
    lv_obj_set_height(ui_isWork, lv_pct(30));
    lv_obj_set_align(ui_isWork, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_isWork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_isWork, lv_color_hex(0xEE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_isWork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblState = lv_label_create(ui_isWork);
    lv_obj_set_width(ui_lblState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblState, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblState, "INACTIVO");
    lv_obj_set_style_text_color(ui_lblState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblState, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgState = lv_img_create(ui_isWork);
    lv_img_set_src(ui_imgState, &ui_img_hibernacion_png);
    lv_obj_set_width(ui_imgState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgState, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_imgState, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgState, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_areaComands = lv_textarea_create(ui_state);
    lv_obj_set_width(ui_areaComands, lv_pct(100));
    lv_obj_set_height(ui_areaComands, lv_pct(60));
    lv_obj_set_align(ui_areaComands, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_text(ui_areaComands, "Comands...");
    lv_textarea_set_placeholder_text(ui_areaComands, "Placeholder...");

    ui_btnStop = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_btnStop, 45);
    lv_obj_set_height(ui_btnStop, 40);
    lv_obj_set_x(ui_btnStop, 110);
    lv_obj_set_y(ui_btnStop, -25);
    lv_obj_set_align(ui_btnStop, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_btnStop);
    lv_img_set_src(ui_Image9, &ui_img_680980976);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnPlay = lv_obj_create(ui_visualize);
    lv_obj_set_width(ui_btnPlay, 45);
    lv_obj_set_height(ui_btnPlay, 40);
    lv_obj_set_x(ui_btnPlay, 50);
    lv_obj_set_y(ui_btnPlay, -25);
    lv_obj_set_align(ui_btnPlay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_btnPlay);
    lv_img_set_src(ui_Image10, &ui_img_324518500);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_controller = lv_obj_create(ui_main);
    lv_obj_set_width(ui_controller, 250);
    lv_obj_set_height(ui_controller, 400);
    lv_obj_set_x(ui_controller, -10);
    lv_obj_set_y(ui_controller, -10);
    lv_obj_set_align(ui_controller, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_controller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnXpos = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnXpos, 70);
    lv_obj_set_height(ui_btnXpos, 50);
    lv_obj_set_x(ui_btnXpos, 70);
    lv_obj_set_y(ui_btnXpos, -96);
    lv_obj_set_align(ui_btnXpos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnXpos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnXpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnXpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnXpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnXpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnXpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnXpos, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnXpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblXpos = lv_label_create(ui_btnXpos);
    lv_obj_set_width(ui_lblXpos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblXpos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblXpos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblXpos, "+X");
    lv_obj_set_style_text_font(ui_lblXpos, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnXneg = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnXneg, 70);
    lv_obj_set_height(ui_btnXneg, 50);
    lv_obj_set_x(ui_btnXneg, -70);
    lv_obj_set_y(ui_btnXneg, -93);
    lv_obj_set_align(ui_btnXneg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnXneg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnXneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnXneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnXneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnXneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnXneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnXneg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnXneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblXneg = lv_label_create(ui_btnXneg);
    lv_obj_set_width(ui_lblXneg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblXneg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblXneg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblXneg, "-X");
    lv_obj_set_style_text_font(ui_lblXneg, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnYpos = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnYpos, 70);
    lv_obj_set_height(ui_btnYpos, 50);
    lv_obj_set_x(ui_btnYpos, 0);
    lv_obj_set_y(ui_btnYpos, -160);
    lv_obj_set_align(ui_btnYpos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnYpos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnYpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnYpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnYpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnYpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnYpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnYpos, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnYpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblYpos = lv_label_create(ui_btnYpos);
    lv_obj_set_width(ui_lblYpos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblYpos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblYpos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYpos, "+Y");
    lv_obj_set_style_text_font(ui_lblYpos, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnYneg = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnYneg, 70);
    lv_obj_set_height(ui_btnYneg, 50);
    lv_obj_set_x(ui_btnYneg, 0);
    lv_obj_set_y(ui_btnYneg, -30);
    lv_obj_set_align(ui_btnYneg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnYneg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnYneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnYneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnYneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnYneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnYneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnYneg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnYneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblYneg = lv_label_create(ui_btnYneg);
    lv_obj_set_width(ui_lblYneg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblYneg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblYneg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYneg, "-Y");
    lv_obj_set_style_text_font(ui_lblYneg, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnZpos = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnZpos, 70);
    lv_obj_set_height(ui_btnZpos, 50);
    lv_obj_set_x(ui_btnZpos, -70);
    lv_obj_set_y(ui_btnZpos, 20);
    lv_obj_set_align(ui_btnZpos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnZpos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnZpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnZpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnZpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnZpos, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnZpos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnZpos, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnZpos, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblZpos = lv_label_create(ui_btnZpos);
    lv_obj_set_width(ui_lblZpos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblZpos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblZpos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblZpos, "+Z");
    lv_obj_set_style_text_font(ui_lblZpos, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnZneg = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnZneg, 70);
    lv_obj_set_height(ui_btnZneg, 50);
    lv_obj_set_x(ui_btnZneg, 78);
    lv_obj_set_y(ui_btnZneg, 20);
    lv_obj_set_align(ui_btnZneg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnZneg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnZneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnZneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnZneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnZneg, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnZneg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnZneg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnZneg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblZneg = lv_label_create(ui_btnZneg);
    lv_obj_set_width(ui_lblZneg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblZneg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblZneg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblZneg, "-Z");
    lv_obj_set_style_text_font(ui_lblZneg, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pasos = lv_dropdown_create(ui_controller);
    lv_dropdown_set_options(ui_pasos, "predetermined\n0.1mm\n1.0mm\n10mm");
    lv_obj_set_width(ui_pasos, 200);
    lv_obj_set_height(ui_pasos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pasos, 0);
    lv_obj_set_y(ui_pasos, 90);
    lv_obj_set_align(ui_pasos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pasos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_stopMachine = lv_btn_create(ui_controller);
    lv_obj_set_width(ui_stopMachine, 230);
    lv_obj_set_height(ui_stopMachine, 50);
    lv_obj_set_align(ui_stopMachine, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_stopMachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stopMachine, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopMachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_stopMachine);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "STOP MACHINE");

    ui_btnHome = lv_obj_create(ui_controller);
    lv_obj_set_width(ui_btnHome, 40);
    lv_obj_set_height(ui_btnHome, 40);
    lv_obj_set_x(ui_btnHome, 0);
    lv_obj_set_y(ui_btnHome, -96);
    lv_obj_set_align(ui_btnHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnHome, lv_color_hex(0xD2C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_btnHome);
    lv_img_set_src(ui_Image4, &ui_img_home_24_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 230);

    lv_obj_add_event_cb(ui_allStop, ui_event_allStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_listMaquinas, ui_event_listMaquinas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_agregarTareas, ui_event_agregarTareas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStop, ui_event_btnStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPlay, ui_event_btnPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnXpos, ui_event_btnXpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnXneg, ui_event_btnXneg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnYpos, ui_event_btnYpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnYneg, ui_event_btnYneg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnZpos, ui_event_btnZpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnZneg, ui_event_btnZneg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopMachine, ui_event_stopMachine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnHome, ui_event_btnHome, LV_EVENT_ALL, NULL);

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_topBar = NULL;
    ui_title = NULL;
    ui_allStop = NULL;
    ui_Label5 = NULL;
    ui_uiLabelStatusConn = NULL;
    ui_machines = NULL;
    ui_listMaquinas = NULL;
    ui_agregarTareas = NULL;
    ui_Label8 = NULL;
    ui_Image1 = NULL;
    ui_visualize = NULL;
    ui_posx = NULL;
    ui_lblposx = NULL;
    ui_posy = NULL;
    ui_lblposy = NULL;
    ui_posz = NULL;
    ui_lblposz = NULL;
    ui_state = NULL;
    ui_isWork = NULL;
    ui_lblState = NULL;
    ui_imgState = NULL;
    ui_areaComands = NULL;
    ui_btnStop = NULL;
    ui_Image9 = NULL;
    ui_btnPlay = NULL;
    ui_Image10 = NULL;
    ui_controller = NULL;
    ui_btnXpos = NULL;
    ui_lblXpos = NULL;
    ui_btnXneg = NULL;
    ui_lblXneg = NULL;
    ui_btnYpos = NULL;
    ui_lblYpos = NULL;
    ui_btnYneg = NULL;
    ui_lblYneg = NULL;
    ui_btnZpos = NULL;
    ui_lblZpos = NULL;
    ui_btnZneg = NULL;
    ui_lblZneg = NULL;
    ui_pasos = NULL;
    ui_stopMachine = NULL;
    ui_Label12 = NULL;
    ui_btnHome = NULL;
    ui_Image4 = NULL;

}

void ui_main_screen_relocalize(void)
{
    // label widgets on screen

}
