// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_main_screen_relocalize(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_topBar;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_allStop;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_uiLabelStatusConn;
extern lv_obj_t * ui_machines;
extern lv_obj_t * ui_listMaquinas;
extern lv_obj_t * ui_agregarTareas;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_visualize;
extern lv_obj_t * ui_posx;
extern lv_obj_t * ui_lblposx;
extern lv_obj_t * ui_posy;
extern lv_obj_t * ui_lblposy;
extern lv_obj_t * ui_posz;
extern lv_obj_t * ui_lblposz;
extern lv_obj_t * ui_state;
extern lv_obj_t * ui_isWork;
extern lv_obj_t * ui_lblState;
extern lv_obj_t * ui_imgState;
extern lv_obj_t * ui_areaComands;
extern lv_obj_t * ui_btnStop;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_btnplay;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_controller;
extern lv_obj_t * ui_btnXpos;
extern lv_obj_t * ui_lblXpos;
extern lv_obj_t * ui_btnXneg;
extern lv_obj_t * ui_lblXneg;
extern lv_obj_t * ui_btnYpos;
extern lv_obj_t * ui_lblYpos;
extern lv_obj_t * ui_btnYneg;
extern lv_obj_t * ui_lblYneg;
extern lv_obj_t * ui_btnZpos;
extern lv_obj_t * ui_lblZpos;
extern lv_obj_t * ui_btnZneg;
extern lv_obj_t * ui_lblZneg;
extern lv_obj_t * ui_pasos;
extern lv_obj_t * ui_stopMachine;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_btnHome;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

