// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#include "../ui.h"

lv_obj_t * ui_seleccionarTarea = NULL;
lv_obj_t * ui_opcionesTareas = NULL;
lv_obj_t * ui_listaTareas1 = NULL;
lv_obj_t * ui_asignarTarea = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_btnAtras = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image5 = NULL;
// event funtions

// build funtions

void ui_seleccionarTarea_screen_init(void)
{
    ui_seleccionarTarea = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_seleccionarTarea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_seleccionarTarea, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_seleccionarTarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_opcionesTareas = lv_obj_create(ui_seleccionarTarea);
    lv_obj_set_width(ui_opcionesTareas, lv_pct(90));
    lv_obj_set_height(ui_opcionesTareas, lv_pct(90));
    lv_obj_set_align(ui_opcionesTareas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_opcionesTareas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_listaTareas1 = lv_roller_create(ui_opcionesTareas);
    lv_roller_set_options(ui_listaTareas1, "Tarea 1\nTarea 2\nTarea 3\nTarea 4\nTarea 5\nTarea 6\nTarea 7",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_listaTareas1, lv_pct(70));
    lv_obj_set_height(ui_listaTareas1, lv_pct(100));
    lv_obj_set_align(ui_listaTareas1, LV_ALIGN_LEFT_MID);

    ui_asignarTarea = lv_btn_create(ui_opcionesTareas);
    lv_obj_set_width(ui_asignarTarea, lv_pct(25));
    lv_obj_set_height(ui_asignarTarea, lv_pct(12));
    lv_obj_set_x(ui_asignarTarea, 0);
    lv_obj_set_y(ui_asignarTarea, -50);
    lv_obj_set_align(ui_asignarTarea, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_asignarTarea, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_asignarTarea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_asignarTarea, lv_color_hex(0x30B129), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_asignarTarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_asignarTarea);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Asignar Tarea");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnAtras = lv_btn_create(ui_opcionesTareas);
    lv_obj_set_width(ui_btnAtras, lv_pct(25));
    lv_obj_set_height(ui_btnAtras, lv_pct(12));
    lv_obj_set_x(ui_btnAtras, 0);
    lv_obj_set_y(ui_btnAtras, 50);
    lv_obj_set_align(ui_btnAtras, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnAtras, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAtras, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_btnAtras);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label7, "Atras");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_btnAtras);
    lv_img_set_src(ui_Image5, &ui_img_745144479);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_seleccionarTarea_screen_destroy(void)
{
    if(ui_seleccionarTarea) lv_obj_del(ui_seleccionarTarea);

    // NULL screen variables
    ui_seleccionarTarea = NULL;
    ui_opcionesTareas = NULL;
    ui_listaTareas1 = NULL;
    ui_asignarTarea = NULL;
    ui_Label6 = NULL;
    ui_btnAtras = NULL;
    ui_Label7 = NULL;
    ui_Image5 = NULL;

}

void ui_seleccionarTarea_screen_relocalize(void)
{
    // label widgets on screen

}
