// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#ifndef UI_SELECCIONARTAREA_H
#define UI_SELECCIONARTAREA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_seleccionarTarea
extern void ui_seleccionarTarea_screen_init(void);
extern void ui_seleccionarTarea_screen_destroy(void);
extern void ui_seleccionarTarea_screen_relocalize(void);
extern lv_obj_t * ui_seleccionarTarea;
extern lv_obj_t * ui_opcionesTareas;
extern lv_obj_t * ui_listaTareas1;
extern void ui_event_asignarTarea(lv_event_t * e);
extern lv_obj_t * ui_asignarTarea;
extern lv_obj_t * ui_Label6;
extern void ui_event_btnAtras(lv_event_t * e);
extern lv_obj_t * ui_btnAtras;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

